import { SetMetadata } from '@nestjs/common';

export const WORKER_OPERATION = 'scm.worker-operation';

export const WORKER_OPERATIONS = [
  'AI_JOB_EXECUTE',
  'BILLING_EVENT_CONSUME',
  'CONTROL_ALERT_EVENT_CONSUME',
  'CONTROL_BI_EVENT_CONSUME',
  'CONTROL_EVENT_CONSUME',
  'CONTROL_RECONCILIATION_EVENT_CONSUME',
  'EVENT_DELIVERY_CLAIM',
  'EVENT_DELIVERY_COMPLETE',
  'EVENT_DELIVERY_FAIL',
  'EVENT_OUTBOX_FAIL',
  'EVENT_OUTBOX_PUBLISH',
  'EVENT_RELAY_CLAIM',
  'INTEGRATION_PORTAL_EVENT_CONSUME',
  'JOB_COMPLETE',
  'JOB_GET',
  'JOB_HEARTBEAT',
  'JOB_PROGRESS',
  'JOB_RUN_CLAIM',
  'JOB_TRIGGER',
  'OMS_FULFILLMENT_EVENT_CONSUME',
  'OMS_TIMELINE_EVENT_CONSUME',
  'OPERATIONS_JOB_EXECUTE',
  'PRINT_JOB_CLAIM',
  'PRINT_JOB_COMPLETE',
  'PRINT_JOB_GET',
  'RECONCILIATION_RUN',
  'TMS_SHIPMENT_EVENT_CONSUME',
  'WEBHOOK_DELIVERY_CLAIM',
  'WEBHOOK_DELIVERY_COMPLETE',
  'WMS_FULFILLMENT_EVENT_CONSUME',
  'WORKER_BACKLOG_READ',
] as const;

export type WorkerOperation = (typeof WORKER_OPERATIONS)[number];

export const WorkerAccessible = (operation: WorkerOperation) =>
  SetMetadata(WORKER_OPERATION, operation);
