ALTER TYPE "wms"."OutboundOrderStatus" ADD VALUE 'PICKING';
CREATE TYPE "wms"."PickTaskStatus" AS ENUM ('OPEN','ASSIGNED','IN_PROGRESS','SHORT_PICK','REVIEWING','COMPLETED','CANCELLED');
CREATE TYPE "wms"."PickMode" AS ENUM ('ORDER','BATCH','SEEDING','ZONE','FULL_CASE','EACH');
CREATE TYPE "wms"."PickScanOutcome" AS ENUM ('ACCEPTED','REJECTED');
CREATE TYPE "wms"."ShortPickStatus" AS ENUM ('OPEN','RESOLVED');
CREATE TYPE "wms"."PickVerificationStatus" AS ENUM ('PASSED','FAILED','CORRECTED');

CREATE TABLE "wms"."pick_task" ("id" UUID PRIMARY KEY,"tenant_id" UUID NOT NULL,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" UUID NOT NULL,"updated_at" TIMESTAMPTZ(3) NOT NULL,"updated_by" UUID NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"status" "wms"."PickTaskStatus" NOT NULL DEFAULT 'OPEN',"task_no" VARCHAR(100) NOT NULL,"wave_id" UUID NOT NULL,"outbound_order_id" UUID,"mode" "wms"."PickMode" NOT NULL,"temperature_zone" VARCHAR(50),"route_version" INTEGER NOT NULL DEFAULT 1,"assigned_to" UUID,"container_code" VARCHAR(200),"workload" DECIMAL(24,6) NOT NULL DEFAULT 0,"started_at" TIMESTAMPTZ(3),"completed_at" TIMESTAMPTZ(3),CONSTRAINT "pick_task_values_valid" CHECK ("version">0 AND "route_version">0 AND "workload">=0 AND ("status"<>'COMPLETED' OR "completed_at" IS NOT NULL)));
CREATE UNIQUE INDEX "pick_task_tenant_no_key" ON "wms"."pick_task"("tenant_id","task_no");
CREATE INDEX "pick_task_workbench_idx" ON "wms"."pick_task"("tenant_id","wave_id","status","created_at");

CREATE TABLE "wms"."pick_task_line" ("id" UUID PRIMARY KEY,"tenant_id" UUID NOT NULL,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" UUID NOT NULL,"updated_at" TIMESTAMPTZ(3) NOT NULL,"updated_by" UUID NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"status" "wms"."WmsRecordStatus" NOT NULL DEFAULT 'ACTIVE',"task_id" UUID NOT NULL,"allocation_id" UUID NOT NULL,"outbound_order_id" UUID NOT NULL,"outbound_line_id" UUID NOT NULL,"balance_id" UUID NOT NULL,"source_location_id" UUID NOT NULL,"product_id" UUID NOT NULL,"handling_unit_id" UUID,"inventory_lot_id" UUID,"serial_number_id" UUID,"required_base" DECIMAL(24,12) NOT NULL,"picked_base" DECIMAL(24,12) NOT NULL DEFAULT 0,"short_base" DECIMAL(24,12) NOT NULL DEFAULT 0,"target_container_code" VARCHAR(200),CONSTRAINT "pick_task_line_values_valid" CHECK ("version">0 AND "required_base">0 AND "picked_base">=0 AND "short_base">=0 AND "picked_base"+"short_base"<="required_base"));
CREATE UNIQUE INDEX "pick_task_line_allocation_key" ON "wms"."pick_task_line"("tenant_id","task_id","allocation_id");
CREATE INDEX "pick_task_line_route_idx" ON "wms"."pick_task_line"("tenant_id","task_id","source_location_id");

CREATE TABLE "wms"."pick_route_version" ("id" UUID PRIMARY KEY,"tenant_id" UUID NOT NULL,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" UUID NOT NULL,"updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_by" UUID NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"status" "wms"."WmsRecordStatus" NOT NULL DEFAULT 'ACTIVE',"task_id" UUID NOT NULL,"route_version" INTEGER NOT NULL,"input_snapshot" JSONB NOT NULL,"route_snapshot" JSONB NOT NULL,CONSTRAINT "pick_route_values_valid" CHECK ("version">0 AND "route_version">0 AND jsonb_typeof("input_snapshot")='object' AND jsonb_typeof("route_snapshot")='object'));
CREATE UNIQUE INDEX "pick_route_task_version_key" ON "wms"."pick_route_version"("tenant_id","task_id","route_version");

CREATE TABLE "wms"."pick_scan_event" ("id" UUID PRIMARY KEY,"tenant_id" UUID NOT NULL,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" UUID NOT NULL,"updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_by" UUID NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"status" "wms"."WmsRecordStatus" NOT NULL DEFAULT 'ACTIVE',"task_id" UUID NOT NULL,"task_line_id" UUID NOT NULL,"device_id" VARCHAR(200) NOT NULL,"device_sequence" BIGINT NOT NULL,"source_location_id" UUID NOT NULL,"product_id" UUID NOT NULL,"handling_unit_id" UUID,"target_container_code" VARCHAR(200) NOT NULL,"quantity_base" DECIMAL(24,12) NOT NULL,"outcome" "wms"."PickScanOutcome" NOT NULL,"rejection_code" VARCHAR(100),"scanned_at" TIMESTAMPTZ(3) NOT NULL,CONSTRAINT "pick_scan_values_valid" CHECK ("version">0 AND "device_sequence">0 AND "quantity_base">0 AND length(btrim("device_id"))>0 AND length(btrim("target_container_code"))>0 AND (("outcome"='REJECTED' AND "rejection_code" IS NOT NULL) OR ("outcome"='ACCEPTED' AND "rejection_code" IS NULL))));
CREATE UNIQUE INDEX "pick_scan_device_sequence_key" ON "wms"."pick_scan_event"("tenant_id","device_id","device_sequence");
CREATE INDEX "pick_scan_task_idx" ON "wms"."pick_scan_event"("tenant_id","task_id","created_at");

CREATE TABLE "wms"."pick_confirmation" ("id" UUID PRIMARY KEY,"tenant_id" UUID NOT NULL,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" UUID NOT NULL,"updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_by" UUID NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"status" "wms"."WmsRecordStatus" NOT NULL DEFAULT 'ACTIVE',"task_id" UUID NOT NULL,"task_line_id" UUID NOT NULL,"scan_event_id" UUID NOT NULL,"quantity_base" DECIMAL(24,12) NOT NULL,"confirmation_snapshot" JSONB NOT NULL,CONSTRAINT "pick_confirmation_values_valid" CHECK ("version">0 AND "quantity_base">0 AND jsonb_typeof("confirmation_snapshot")='object'));
CREATE UNIQUE INDEX "pick_confirmation_scan_key" ON "wms"."pick_confirmation"("tenant_id","scan_event_id");
CREATE INDEX "pick_confirmation_line_idx" ON "wms"."pick_confirmation"("tenant_id","task_line_id","created_at");

CREATE TABLE "wms"."short_pick_case" ("id" UUID PRIMARY KEY,"tenant_id" UUID NOT NULL,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" UUID NOT NULL,"updated_at" TIMESTAMPTZ(3) NOT NULL,"updated_by" UUID NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"status" "wms"."ShortPickStatus" NOT NULL DEFAULT 'OPEN',"case_no" VARCHAR(100) NOT NULL,"task_id" UUID NOT NULL,"task_line_id" UUID NOT NULL,"short_base" DECIMAL(24,12) NOT NULL,"reason_code" VARCHAR(100) NOT NULL,"reason" VARCHAR(500) NOT NULL,"options_snapshot" JSONB NOT NULL,"resolution_type" VARCHAR(100),"resolution_snapshot" JSONB,"resolved_at" TIMESTAMPTZ(3),CONSTRAINT "short_pick_values_valid" CHECK ("version">0 AND "short_base">0 AND length(btrim("reason_code"))>0 AND length(btrim("reason"))>0 AND jsonb_typeof("options_snapshot")='object' AND ("status"<>'RESOLVED' OR ("resolution_type" IS NOT NULL AND "resolution_snapshot" IS NOT NULL AND "resolved_at" IS NOT NULL))));
CREATE UNIQUE INDEX "short_pick_line_key" ON "wms"."short_pick_case"("tenant_id","task_line_id");
CREATE UNIQUE INDEX "short_pick_tenant_no_key" ON "wms"."short_pick_case"("tenant_id","case_no");
CREATE INDEX "short_pick_workbench_idx" ON "wms"."short_pick_case"("tenant_id","status","created_at");

CREATE TABLE "wms"."pick_verification_result" ("id" UUID PRIMARY KEY,"tenant_id" UUID NOT NULL,"created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" UUID NOT NULL,"updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_by" UUID NOT NULL,"version" INTEGER NOT NULL DEFAULT 1,"status" "wms"."PickVerificationStatus" NOT NULL,"task_id" UUID NOT NULL,"scope_type" VARCHAR(50) NOT NULL,"scope_ref" VARCHAR(200) NOT NULL,"expected_snapshot" JSONB NOT NULL,"actual_snapshot" JSONB NOT NULL,"variance_snapshot" JSONB NOT NULL,"correction_type" VARCHAR(100),"corrected_at" TIMESTAMPTZ(3),CONSTRAINT "pick_verification_values_valid" CHECK ("version">0 AND jsonb_typeof("expected_snapshot")='object' AND jsonb_typeof("actual_snapshot")='object' AND jsonb_typeof("variance_snapshot")='object'));
CREATE INDEX "pick_verification_task_idx" ON "wms"."pick_verification_result"("tenant_id","task_id","created_at");

CREATE TRIGGER "pick_route_version_immutable" BEFORE UPDATE OR DELETE ON "wms"."pick_route_version" FOR EACH ROW EXECUTE FUNCTION "wms"."reject_receiving_fact_mutation"();
CREATE TRIGGER "pick_scan_event_immutable" BEFORE UPDATE OR DELETE ON "wms"."pick_scan_event" FOR EACH ROW EXECUTE FUNCTION "wms"."reject_receiving_fact_mutation"();
CREATE TRIGGER "pick_confirmation_immutable" BEFORE UPDATE OR DELETE ON "wms"."pick_confirmation" FOR EACH ROW EXECUTE FUNCTION "wms"."reject_receiving_fact_mutation"();
CREATE TRIGGER "pick_verification_result_immutable" BEFORE UPDATE OR DELETE ON "wms"."pick_verification_result" FOR EACH ROW EXECUTE FUNCTION "wms"."reject_receiving_fact_mutation"();
